#!/usr/bin/env bash

set -euo pipefail
CURRENT_DIR="$(realpath "$(dirname "$0")")"
cd "${CURRENT_DIR}"

export LANG=C
export LC_ALL=C
date
set +e
"${CURRENT_DIR}/vendor/bin/phpstan" analyse --configuration="${CURRENT_DIR}/phpstan.neon" "$@"
RESULT=$?
date
echo "$SECONDS sec"
exit "$RESULT"
