<?php

declare(strict_types=1);

namespace SmsTelnyx;

/**
 * Configuration: ucrm.json (generated by CRM) + data/config.json (plugin settings form).
 */
final class Config
{
    private static ?array $data = null;

    public static function all(): array
    {
        if (self::$data === null) {
            self::$data = array_merge(self::json(PLUGIN_ROOT . '/ucrm.json'), self::json(PLUGIN_ROOT . '/data/config.json'));
        }
        return self::$data;
    }

    public static function get(string $key, $default = null)
    {
        $v = self::all()[$key] ?? null;
        return ($v === null || $v === '') ? $default : $v;
    }

    public static function str(string $key, string $default = ''): string
    {
        return trim((string) self::get($key, $default));
    }

    public static function bool(string $key): bool
    {
        $v = self::get($key, false);
        return $v === true || $v === 1 || $v === '1' || $v === 'true';
    }

    public static function ucrmUrl(): string
    {
        $u = (string) (self::get('ucrmLocalUrl') ?: self::get('ucrmPublicUrl', ''));
        return $u === '' ? '' : rtrim($u, '/') . '/';
    }

    public static function unmsUrl(): string
    {
        $u = (string) self::get('unmsLocalUrl', '');
        return $u === '' ? '' : rtrim($u, '/') . '/';
    }

    /** For tests. */
    public static function override(array $data): void
    {
        self::$data = $data;
    }

    private static function json(string $file): array
    {
        if (! is_file($file)) {
            return [];
        }
        $d = json_decode((string) file_get_contents($file), true);
        return is_array($d) ? $d : [];
    }
}

/**
 * Appends to data/plugin.log (shown on the plugin page in CRM). Trims itself to ~256 KB.
 */
final class Log
{
    private const MAX = 262144;

    public static function info(string $m): void { self::write('INFO', $m); }
    public static function warn(string $m): void { self::write('WARN', $m); }
    public static function error(string $m): void { self::write('ERROR', $m); }

    public static function debug(string $m): void
    {
        if (Config::bool('logging_level')) {
            self::write('DEBUG', $m);
        }
    }

    private static function write(string $level, string $m): void
    {
        $file = PLUGIN_ROOT . '/data/plugin.log';
        $line = sprintf("[%s] %s %s\n", date('Y-m-d H:i:s'), $level, $m);
        @file_put_contents($file, $line, FILE_APPEND | LOCK_EX);
        if (@filesize($file) > self::MAX) {
            $tail = substr((string) file_get_contents($file), -intdiv(self::MAX, 2));
            @file_put_contents($file, "[log trimmed]\n" . substr($tail, (int) strpos($tail, "\n") + 1), LOCK_EX);
        }
    }
}

final class HttpException extends \RuntimeException
{
    public function __construct(string $message, public readonly int $status = 0, public readonly ?array $body = null)
    {
        parent::__construct($message, $status);
    }
}

/**
 * Minimal JSON-over-HTTP client (curl). Swappable for tests via Http::$transport.
 */
final class Http
{
    /** @var null|callable(string $method, string $url, array $headers, ?string $body): array{0:int,1:string} */
    public static $transport = null;

    public static function request(string $method, string $url, array $headers = [], $body = null, bool $verify = true): array
    {
        $payload = $body === null ? null : (is_string($body) ? $body : json_encode($body, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE));
        if ($payload !== null) {
            $headers[] = 'Content-Type: application/json';
        }
        $headers[] = 'Accept: application/json';

        if (self::$transport) {
            [$status, $raw] = (self::$transport)($method, $url, $headers, $payload);
        } else {
            $c = curl_init($url);
            curl_setopt_array($c, [
                CURLOPT_CUSTOMREQUEST => $method,
                CURLOPT_HTTPHEADER => $headers,
                CURLOPT_RETURNTRANSFER => true,
                CURLOPT_TIMEOUT => 45,
                CURLOPT_CONNECTTIMEOUT => 10,
                CURLOPT_SSL_VERIFYPEER => $verify,
                CURLOPT_SSL_VERIFYHOST => $verify ? 2 : 0,
            ]);
            if ($payload !== null) {
                curl_setopt($c, CURLOPT_POSTFIELDS, $payload);
            }
            $raw = curl_exec($c);
            $err = curl_error($c);
            $status = (int) curl_getinfo($c, CURLINFO_RESPONSE_CODE);
            curl_close($c);
            if ($raw === false) {
                throw new HttpException(sprintf('%s %s failed: %s', $method, self::redact($url), $err));
            }
        }
        $json = json_decode((string) $raw, true);
        if ($status >= 400) {
            throw new HttpException(sprintf('%s %s → HTTP %d: %s', $method, self::redact($url), $status, substr((string) $raw, 0, 300)),
                $status, is_array($json) ? $json : null);
        }
        return is_array($json) ? $json : [];
    }

    /** True when TLS verification should be skipped (https://localhost with self-signed cert). */
    public static function isSecureLocalhost(string $url): bool
    {
        $p = parse_url($url);
        return $p && in_array(strtolower($p['host'] ?? ''), ['localhost', '127.0.0.1'], true) && strtolower($p['scheme'] ?? '') === 'https';
    }

    private static function redact(string $url): string
    {
        return preg_replace('~\?.*$~', '?…', $url) ?? $url;
    }
}

/**
 * UISP CRM API (with the plugin's own app key) and UISP NMS API (with an optional token).
 */
final class Crm
{
    public static function get(string $endpoint, array $query = []): array
    {
        $base = Config::ucrmUrl();
        if ($base === '') {
            throw new \RuntimeException('CRM URL missing from ucrm.json');
        }
        $url = $base . 'api/v1.0/' . ltrim($endpoint, '/') . ($query ? '?' . self::query($query) : '');
        return Http::request('GET', $url, ['X-Auth-App-Key: ' . Config::str('pluginAppKey')], null, ! Http::isSecureLocalhost($url));
    }

    /** Fetches every page of a list endpoint. */
    public static function all(string $endpoint, array $query = []): array
    {
        $out = [];
        $offset = 0;
        do {
            $batch = self::get($endpoint, $query + ['limit' => 500, 'offset' => $offset]);
            $out = array_merge($out, $batch);
            $offset += 500;
        } while (count($batch) === 500);
        return $out;
    }

    public static function nmsAvailable(): bool
    {
        return Config::str('uispApiToken') !== '' && Config::unmsUrl() !== '';
    }

    public static function nms(string $endpoint, array $query = []): array
    {
        $url = Config::unmsUrl() . 'api/v2.1/' . ltrim($endpoint, '/') . ($query ? '?' . self::query($query) : '');
        return Http::request('GET', $url, ['x-auth-token: ' . Config::str('uispApiToken')], null, ! Http::isSecureLocalhost($url));
    }

    /** http_build_query, but repeated keys as statuses[]=1&statuses[]=2. */
    private static function query(array $q): string
    {
        $parts = [];
        foreach ($q as $k => $v) {
            foreach ((array) $v as $item) {
                $parts[] = rawurlencode(is_array($v) ? $k . '[]' : (string) $k) . '=' . rawurlencode((string) $item);
            }
        }
        return implode('&', $parts);
    }
}

/**
 * JSON files under data/ with exclusive locking.
 */
final class Store
{
    public static function path(string $name): string
    {
        $dir = PLUGIN_ROOT . '/data/store';
        if (! is_dir($dir)) {
            @mkdir($dir, 0775, true);
        }
        return $dir . '/' . preg_replace('~[^a-zA-Z0-9_.-]~', '', $name) . '.json';
    }

    public static function read(string $name, array $default = []): array
    {
        $f = self::path($name);
        if (! is_file($f)) {
            return $default;
        }
        $d = json_decode((string) file_get_contents($f), true);
        return is_array($d) ? $d : $default;
    }

    /** Atomically read-modify-write. $fn receives the current array and returns the new one. */
    public static function update(string $name, callable $fn, array $default = []): array
    {
        $f = self::path($name);
        $h = fopen($f, 'c+');
        if (! $h) {
            throw new \RuntimeException('Cannot open store ' . $name);
        }
        try {
            flock($h, LOCK_EX);
            $raw = stream_get_contents($h);
            $cur = $raw ? (json_decode($raw, true) ?: $default) : $default;
            $new = $fn($cur);
            ftruncate($h, 0);
            rewind($h);
            fwrite($h, (string) json_encode($new, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE));
            fflush($h);
            return $new;
        } finally {
            flock($h, LOCK_UN);
            fclose($h);
        }
    }

    public static function delete(string $name): void
    {
        @unlink(self::path($name));
    }
}
